// exporters/flutter.js
// Exports design_tokens.dart for Flutter

export function exportFlutter(state) {
  const cl = state.color.light;
  const cd = state.color.dark;
  const ty = state.typography;
  const sp = state.spacing;
  const ra = state.radius;

  function hexToFlutter(hex) {
    const h = hex.replace('#', '');
    if (h.length === 6) return `const Color(0xFF${h.toUpperCase()})`;
    return `const Color(0xFF${h.toUpperCase()})`;
  }

  function remToDp(rem) {
    const val = parseFloat(rem);
    return isNaN(val) ? '16.0' : (val * 16).toFixed(1);
  }

  const dart = `// design_tokens.dart — ${state.meta.appName}
// Generated by design-system skill
// Form factor: ${state.meta.formFactor} | App type: ${state.meta.appType}

import 'package:flutter/material.dart';

class AppColors {
  AppColors._();

  // Light Mode
  static const Color bg             = ${hexToFlutter(cl.bg)};
  static const Color surface        = ${hexToFlutter(cl.surface)};
  static const Color surface2       = ${hexToFlutter(cl.surface2)};
  static const Color surfaceOffset  = ${hexToFlutter(cl.surfaceOffset)};
  static const Color text           = ${hexToFlutter(cl.text)};
  static const Color textMuted      = ${hexToFlutter(cl.textMuted)};
  static const Color textFaint      = ${hexToFlutter(cl.textFaint)};
  static const Color primary        = ${hexToFlutter(cl.primary)};
  static const Color primaryHover   = ${hexToFlutter(cl.primaryHover)};
  static const Color error          = ${hexToFlutter(cl.error)};
  static const Color warning        = ${hexToFlutter(cl.warning)};
  static const Color success        = ${hexToFlutter(cl.success)};
  static const Color border         = Color(0x1F000000); // ~12% opacity
  static const Color divider        = Color(0x12000000); // ~7% opacity

  // Dark Mode
  static const Color bgDark             = ${hexToFlutter(cd.bg)};
  static const Color surfaceDark        = ${hexToFlutter(cd.surface)};
  static const Color surface2Dark       = ${hexToFlutter(cd.surface2)};
  static const Color surfaceOffsetDark  = ${hexToFlutter(cd.surfaceOffset)};
  static const Color textDark           = ${hexToFlutter(cd.text)};
  static const Color textMutedDark      = ${hexToFlutter(cd.textMuted)};
  static const Color textFaintDark      = ${hexToFlutter(cd.textFaint)};
  static const Color primaryDark        = ${hexToFlutter(cd.primary)};
  static const Color errorDark          = ${hexToFlutter(cd.error)};
  static const Color warningDark        = ${hexToFlutter(cd.warning)};
  static const Color successDark        = ${hexToFlutter(cd.success)};
}

class AppSpacing {
  AppSpacing._();

  static const double s1  = ${remToDp(sp.s1)};
  static const double s2  = ${remToDp(sp.s2)};
  static const double s3  = ${remToDp(sp.s3)};
  static const double s4  = ${remToDp(sp.s4)};
  static const double s6  = ${remToDp(sp.s6)};
  static const double s8  = ${remToDp(sp.s8)};
  static const double s12 = ${remToDp(sp.s12)};
  static const double s16 = ${remToDp(sp.s16)};
  static const double s20 = ${remToDp(sp.s20)};
  static const double s24 = ${remToDp(sp.s24)};
}

class AppRadius {
  AppRadius._();

  static const double sm   = ${remToDp(ra.sm)};
  static const double md   = ${remToDp(ra.md)};
  static const double lg   = ${remToDp(ra.lg)};
  static const double xl   = ${remToDp(ra.xl)};
  static const double full = 9999.0;
}

class AppTextStyles {
  AppTextStyles._();

  static const String fontDisplay = '${ty.fontDisplay}';
  static const String fontBody    = '${ty.fontBody}';

  static TextStyle displayLarge(BuildContext ctx) => TextStyle(
    fontFamily: fontDisplay,
    fontSize: 40,
    fontWeight: FontWeight.w700,
    color: Theme.of(ctx).brightness == Brightness.dark
      ? AppColors.textDark : AppColors.text,
  );

  static TextStyle bodyMedium(BuildContext ctx) => TextStyle(
    fontFamily: fontBody,
    fontSize: 16,
    fontWeight: FontWeight.w400,
    color: Theme.of(ctx).brightness == Brightness.dark
      ? AppColors.textDark : AppColors.text,
  );
}

class AppTheme {
  AppTheme._();

  static ThemeData light() => ThemeData(
    useMaterial3: true,
    brightness: Brightness.light,
    scaffoldBackgroundColor: AppColors.bg,
    colorScheme: ColorScheme.light(
      primary:   AppColors.primary,
      surface:   AppColors.surface,
      error:     AppColors.error,
      onPrimary: Colors.white,
      onSurface: AppColors.text,
    ),
    fontFamily: AppTextStyles.fontBody,
  );

  static ThemeData dark() => ThemeData(
    useMaterial3: true,
    brightness: Brightness.dark,
    scaffoldBackgroundColor: AppColors.bgDark,
    colorScheme: ColorScheme.dark(
      primary:   AppColors.primaryDark,
      surface:   AppColors.surfaceDark,
      error:     AppColors.errorDark,
      onPrimary: Colors.white,
      onSurface: AppColors.textDark,
    ),
    fontFamily: AppTextStyles.fontBody,
  );
}
`;

  import("./tokens-json.js").then(m => m.downloadFile("design_tokens.dart", dart, "text/plain"));
}
