// exporters/tailwind.js
// Exports tailwind.config.js theme extension

export function exportTailwind(state) {
  const cl = state.color.light;
  const ty = state.typography;
  const sp = state.spacing;
  const ra = state.radius;

  const config = `// tailwind.config.js — ${state.meta.appName}
// Generated by design-system skill

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg:             '${cl.bg}',
        surface:        '${cl.surface}',
        'surface-2':    '${cl.surface2}',
        'surface-off':  '${cl.surfaceOffset}',
        text:           '${cl.text}',
        'text-muted':   '${cl.textMuted}',
        'text-faint':   '${cl.textFaint}',
        primary:        '${cl.primary}',
        'primary-h':    '${cl.primaryHover}',
        error:          '${cl.error}',
        warning:        '${cl.warning}',
        success:        '${cl.success}',
      },
      fontFamily: {
        display: ['${ty.fontDisplay}', 'sans-serif'],
        body:    ['${ty.fontBody}', 'sans-serif'],
      },
      fontSize: {
        xs:   '${ty.scale.xs}',
        sm:   '${ty.scale.sm}',
        base: '${ty.scale.base}',
        lg:   '${ty.scale.lg}',
        xl:   '${ty.scale.xl}',
        '2xl':'${ty.scale["2xl"]}',
      },
      spacing: {
        1:  '${sp.s1}',
        2:  '${sp.s2}',
        3:  '${sp.s3}',
        4:  '${sp.s4}',
        6:  '${sp.s6}',
        8:  '${sp.s8}',
        12: '${sp.s12}',
        16: '${sp.s16}',
        20: '${sp.s20}',
        24: '${sp.s24}',
      },
      borderRadius: {
        sm:   '${ra.sm}',
        md:   '${ra.md}',
        lg:   '${ra.lg}',
        xl:   '${ra.xl}',
        full: '9999px',
      },
    },
  },
};
`;

  import("./tokens-json.js").then(m => m.downloadFile("tailwind.config.js", config, "text/javascript"));
}
